### PR TITLE
define tibble package for as_tibble function

### PR DESCRIPTION
**Pull request by Br-Johnson**
hidden package dependency was causing issues. I don't think I can commit right to master so Chris I think you might be able to merge my pull request.

### CODE REVIEW

**Comment by chrishakai** [comment]
Brett, I made you admin on this repository. I'm not sure why it requires you to get me to approve the changes and merge to master. You should be able to do that now.

**Comment by fostermh** [comment]
its because you are the owner or admin.

Could you also make me an admin for that repo please.

Thanks,

Matthew Foster
Hakai Institute, Calvert Island, BC, Canada / www.hakai.org
Tula Foundation, Quadra Island, BC, Canada / www.tula.org

**Comment by chrishakai** [comment]
Matt, Nate, Ray, Brett and Me are all admins on this repo.

**Comment by fostermh** [comment]
o dang, I was signed in as the wrong user again. sorry about that.

Matthew Foster
Hakai Institute, Calvert Island, BC, Canada / www.hakai.org
Tula Foundation, Quadra Island, BC, Canada / www.tula.org

**Comment by chrishakai** [comment]
And Finn too!

**Pull request merged**
